# Generated by Django 4.0.3 on 2022-04-02 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_alter_photo_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='choose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choosen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='photo',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
