# Generated by Django 4.0.3 on 2022-04-02 12:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0005_album_choose_album_private_alter_photo_choose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='choose',
        ),
        migrations.AddField(
            model_name='album',
            name='choose',
            field=models.ManyToManyField(related_name='choose_albums', to=settings.AUTH_USER_MODEL),
        ),
    ]
